[CmdletBinding()]
param([switch]$Check)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Xml.Linq
$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$viewsRoot = Join-Path $repoRoot 'src/DeskBoxWhite/Views'
$outputPath = Join-Path $repoRoot 'src/DeskBoxWhite/Services/SettingsSearchCatalog.cs'
$xamlNamespace = [System.Xml.Linq.XNamespace]'http://schemas.microsoft.com/winfx/2006/xaml'
$serviceNamespace = [System.Xml.Linq.XNamespace]'using:DeskBoxWhite.Services'
$sectionNamespace = 'using:DeskBoxWhite.Views.SettingsSections'

function Get-SearchEntries([System.Xml.Linq.XElement]$Element, [string]$SectionTag) {
    $typeName = $Element.Name.LocalName
    # Template instances depend on user data and are not independently addressable settings.
    if ($typeName -in @('DataTemplate', 'ControlTemplate', 'ResourceDictionary') -or
        $typeName.EndsWith('.Resources')) { return }

    $header = $Element.Attribute($serviceNamespace + 'Localized.HeaderKey')
    if ($null -ne $header -and -not [string]::IsNullOrWhiteSpace($header.Value)) {
        $description = $Element.Attribute($serviceNamespace + 'Localized.DescriptionKey')
        [PSCustomObject]@{
            SectionTag = $SectionTag
            HeaderKey = $header.Value
            DescriptionKey = if ($null -ne $description) { $description.Value } else { $null }
        }
    }

    if ($Element.Name.NamespaceName -eq $sectionNamespace) {
        $sectionDocument = [System.Xml.Linq.XDocument]::Load(
            (Join-Path $viewsRoot "SettingsSections/$typeName.xaml"))
        Get-SearchEntries $sectionDocument.Root $SectionTag
    }
    foreach ($child in $Element.Elements()) {
        Get-SearchEntries $child $SectionTag
    }
}

function Format-CSharpString([AllowNull()][string]$Value) {
    if ([string]::IsNullOrEmpty($Value)) { return 'null' }
    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

$document = [System.Xml.Linq.XDocument]::Load((Join-Path $viewsRoot 'SettingsWindow.xaml'))
$hostElement = $document.Descendants() | Where-Object {
    $attribute = $_.Attribute($xamlNamespace + 'Name')
    $null -ne $attribute -and $attribute.Value -eq 'ContentHost'
} | Select-Object -First 1
if ($null -eq $hostElement) { throw 'Settings ContentHost was not found.' }

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by scripts/update-settings-search-catalog.ps1. Do not edit by hand.')
$lines.Add('// Only localization keys are retained; no XAML objects are created or referenced.')
$lines.Add('namespace DeskBoxWhite.Services;')
$lines.Add('')
$lines.Add('internal sealed record SettingsSearchCatalogEntry(')
$lines.Add('    string SectionTag, string HeaderKey, string? DescriptionKey);')
$lines.Add('')
$lines.Add('internal static class SettingsSearchCatalog')
$lines.Add('{')
$lines.Add('    internal static IReadOnlyList<SettingsSearchCatalogEntry> Entries { get; } =')
$lines.Add('    [')
$sectionElements = @($hostElement.Elements() | Where-Object {
    $name = $_.Attribute($xamlNamespace + 'Name')
    $null -ne $name -and $name.Value.EndsWith('Section')
})
foreach ($template in $hostElement.Descendants() | Where-Object {
    $key = $_.Attribute($xamlNamespace + 'Key')
    $_.Name.LocalName -eq 'DataTemplate' -and $null -ne $key -and $key.Value.EndsWith('SectionTemplate')
}) {
    $sectionElements += @($template.Elements())
}
foreach ($section in $sectionElements) {
    $nameAttribute = $section.Attribute($xamlNamespace + 'Name')
    if ($null -eq $nameAttribute -or -not $nameAttribute.Value.EndsWith('Section')) { continue }
    $tag = $nameAttribute.Value.Substring(0, $nameAttribute.Value.Length - 'Section'.Length)
    $headers = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
    foreach ($entry in @(Get-SearchEntries $section $tag)) {
        if (-not $headers.Add($entry.HeaderKey)) { continue }
        $lines.Add('        new(' + (Format-CSharpString $entry.SectionTag) + ', ' +
            (Format-CSharpString $entry.HeaderKey) + ', ' +
            (Format-CSharpString $entry.DescriptionKey) + '),')
    }
}
$lines.Add('    ];')
$lines.Add('}')
$text = ($lines -join "`n") + "`n"
if ($Check) {
    if (-not (Test-Path -LiteralPath $outputPath) -or
        [System.IO.File]::ReadAllText($outputPath).Replace("`r`n", "`n") -cne $text) {
        throw 'Settings search catalog is stale. Run scripts/update-settings-search-catalog.ps1.'
    }
    Write-Output 'Settings search catalog matches the XAML.'
} else {
    [System.IO.File]::WriteAllText($outputPath, $text, [System.Text.UTF8Encoding]::new($false))
    Write-Output "Updated $outputPath"
}
